import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter"
import type { Metadata } from "next"

import { Roboto } from "next/font/google"

import { Providers } from "components/providers/Providers"

export const metadata: Metadata = {
  title: "Singapur Airline",
  description: "Generated by create next app",
}

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Providers>
          <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
        </Providers>
      </body>
    </html>

    // <html lang="en">
    //   <body>
    //     <body>{children}</body>
    //     <Header />
    //     {children}
    //     <Footer />
    //   </body>
    // </html>
  )
}
